version: '3.7'

networks:
  challenge:
    driver: bridge

services:
  api:
    image: node:14-alpine
    working_dir: /usr/src/app
    command: sh -c "yarn install && yarn dev"
    networks:
      - challenge
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - DATABASE_URL=mongodb://root:app@localhost:27017/app?authSource=admin&readPreference=primary&retryWrites=false
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: app
    ports:
      - '27017:27017'
    volumes:
      - ./.docker/volumes/mongodb:/data/db
    networks:
      - challenge
