name: Deploy Challenge SKY
    push:
        branches: [develop]     

jobs: 
    challenge_sky:
        runs-on: ubuntu-latest

        steps:

        - uses: actions/checkout@v2 

        - name: QEMU
          uses: docker/setup-qemu-action@v1

        - name: Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Dockerhub
          uses: docker/login-action@v1
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            context: .
            file: ./Dockerfile
            plataforms: linux/amd64, linux/arm64, linux/386
            tags: paulohenryjr/challenge-sky:latest

        - name: install doctl
          uses: digitalocean/action-doctl@v2
          with: 
            token: ${{secrets.DIGITALOCEAN_TOKEN}}
        

        - name: Setup kubectl
          uses: matootie/dokube@v1.3.2
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'  
          with:
            personalAccessToken: ${{secrets.DIGITALOCEAN_TOKEN}}
            clusterName: k8s-anpec

        - name: update yaml kubernetes
          run: kubectl apply -f ./k8s/deployment.yaml 
